'use strict';

// ── NSE F&O liquid universe (top 20 by OI/volume) ──
const NSE_FNO_LIQUID = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
    'BAJFINANCE.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'AXISBANK.NS', 'KOTAKBANK.NS',
    'LT.NS', 'TATAMOTORS.NS', 'ADANIENT.NS', 'WIPRO.NS', 'HCLTECH.NS',
    'TATASTEEL.NS', 'JSWSTEEL.NS', 'HINDALCO.NS', 'ONGC.NS', 'MARUTI.NS',
];

// ── NIFTY 100 + Midcap representative universe (live tape & breadth) ──
const NIFTY100_LIST = [
    // NIFTY 50
    'RELIANCE.NS','TCS.NS','HDFCBANK.NS','INFY.NS','ICICIBANK.NS','HINDUNILVR.NS','ITC.NS',
    'SBIN.NS','BHARTIARTL.NS','KOTAKBANK.NS','LT.NS','AXISBANK.NS','ASIANPAINT.NS','MARUTI.NS',
    'TITAN.NS','WIPRO.NS','BAJFINANCE.NS','ONGC.NS','NTPC.NS','POWERGRID.NS','SUNPHARMA.NS',
    'HCLTECH.NS','TECHM.NS','BAJAJFINSV.NS','CIPLA.NS','DRREDDY.NS','EICHERMOT.NS',
    'TATAMOTORS.NS','TATASTEEL.NS','JSWSTEEL.NS','COALINDIA.NS','GRASIM.NS','DIVISLAB.NS',
    'BPCL.NS','HEROMOTOCO.NS','SBILIFE.NS','HDFCLIFE.NS','NESTLEIND.NS','ADANIPORTS.NS',
    'ULTRACEMCO.NS','INDUSINDBK.NS','APOLLOHOSP.NS','TRENT.NS','BAJAJ-AUTO.NS','SHREECEM.NS',
    'M&M.NS','UPL.NS','BRITANNIA.NS','TATACONSUM.NS','ADANIENT.NS','HINDALCO.NS',
    // NIFTY Next 50
    'DMART.NS','ZOMATO.NS','IRCTC.NS','DLF.NS','HAVELLS.NS','GODREJCP.NS','COLPAL.NS',
    'MARICO.NS','SIEMENS.NS','TATAPOWER.NS','PIDILITE.NS','MUTHOOTFIN.NS','NAUKRI.NS',
    'GAIL.NS','IOC.NS','PNB.NS','CANBK.NS','FEDERALBNK.NS','CHOLAFIN.NS','INDUSTOWER.NS',
    'BEL.NS','NMDC.NS','SAIL.NS','HINDZINC.NS','LUPIN.NS','TORNTPHARM.NS','AUROPHARMA.NS',
    'GODREJPROP.NS','AMBUJACEM.NS','BIOCON.NS','CONCOR.NS','BANDHANBNK.NS','MPHASIS.NS',
    'OFSS.NS','PAGEIND.NS','POLYCAB.NS','VEDL.NS','BALKRISIND.NS','SBICARD.NS','ICICIPRULI.NS',
    // Large/Mid Cap additions
    'JUBLFOOD.NS','BERGEPAINT.NS','CUMMINSIND.NS','ATGL.NS','MOTHERSON.NS','JKCEMENT.NS',
    'PGHH.NS','MFSL.NS','ABBOTINDIA.NS','ATUL.NS',
    // NIFTY Midcap 150 additions
    'LTIM.NS','PERSISTENT.NS','COFORGE.NS','ANGELONE.NS','PAYTM.NS','ZYDUSLIFE.NS',
    'ALKEM.NS','IPCALAB.NS','GLAXO.NS','PFIZER.NS','VOLTAS.NS','WHIRLPOOL.NS',
    'BLUESTARCO.NS','SYMPHONY.NS','KAJARIA.NS','SUPREMEIND.NS','ASTRAL.NS',
    'APOLLOTYRE.NS','MRF.NS','CEATLTD.NS','ESCORTS.NS','TIINDIA.NS','SCHAEFFLER.NS',
    'NHPC.NS','SJVN.NS','RVNL.NS','IRFC.NS','HUDCO.NS','ADANIGREEN.NS',
    'TORNTPOWER.NS','CESC.NS','NATIONALUM.NS','HINDCOPPER.NS','MOIL.NS',
    'KPITTECH.NS','TATAELXSI.NS','LTTS.NS','CYIENT.NS','IDFCFIRSTB.NS',
    'AUBANK.NS','RBLBANK.NS','KARURVYSYA.NS','DCBBANK.NS','ICICIGI.NS',
    'HDFCAMC.NS','LICI.NS','RECLTD.NS','PFC.NS','DELHIVERY.NS',
    'MAXHEALTH.NS','FORTIS.NS','NYKAA.NS','POLICYBZR.NS','MAPMYINDIA.NS',
];

// ── Key NSE index names for the indices bar ──
const NSE_KEY_IDX = [
    'NIFTY 50','NIFTY BANK','INDIA VIX','S&P BSE SENSEX','NIFTY MIDCAP 100',
    'NIFTY SMALLCAP 100','NIFTY IT','NIFTY AUTO','NIFTY PHARMA','NIFTY FMCG',
    'NIFTY METAL','NIFTY ENERGY','NIFTY REALTY','NIFTY INFRA','NIFTY MEDIA',
    'NIFTY NEXT 50','NIFTY 100','NIFTY FINANCIAL SERVICES','NIFTY PSU BANK',
    'NIFTY PRIVATE BANK','NIFTY HEALTHCARE INDEX','NIFTY CONSUMER DURABLES',
];

// ── NSE index name → Yahoo Finance symbol ──
const NSE_IDX_MAP = {
    'NIFTY 50':      { sym: '^NSEI',     name: 'NIFTY 50'   },
    'NIFTY BANK':    { sym: '^NSEBANK',  name: 'Nifty Bank' },
    'INDIA VIX':     { sym: '^INDIAVIX', name: 'India VIX'  },
    'S&P BSE SENSEX':{ sym: '^BSESN',   name: 'BSE SENSEX' },
};

// ── Country ISO → Yahoo index tickers ──
const COUNTRY_INDICES = {
    IND: ['^NSEI', '^NSEBANK', '^BSESN', '^INDIAVIX'],
    USA: ['^DJI', '^GSPC', '^IXIC', '^VIX'],
    JPN: ['^N225'],
    GBR: ['^FTSE'],
    DEU: ['^GDAXI'],
    FRA: ['^FCHI'],
    CHN: ['000001.SS', '^HSI'],
    HKG: ['^HSI', '^HSCE'],
    AUS: ['^AXJO'],
    CAN: ['^GSPTSE'],
    BRA: ['^BVSP'],
    KOR: ['^KS11'],
    TWN: ['^TWII'],
    SGP: ['^STI'],
    ITA: ['FTSEMIB.MI'],
    ESP: ['^IBEX'],
    NLD: ['^AEX'],
    CHE: ['^SSMI'],
    SAU: ['^TASI.SR'],
    MEX: ['^MXX'],
    ARG: ['^MERV'],
    IDN: ['^JKSE'],
    THA: ['^SET.BK'],
    ZAF: ['^J203.JO'],
    POL: ['^WIG20'],
    SWE: ['^OMX'],
    TUR: ['^XU100'],
    RUS: ['IMOEX.ME'],
    ISR: ['^TA125.TA'],
    NOR: ['OBX.OL'],
    MYS: ['^KLSE'],
    PAK: ['^KSE100'],
    PHL: ['PSEi.PS'],
};

// ── Sector breadth stock universe ──
const SECTOR_MAP = {
    'Banking':        ['HDFCBANK.NS','ICICIBANK.NS','KOTAKBANK.NS','AXISBANK.NS','SBIN.NS','INDUSINDBK.NS','BANDHANBNK.NS','FEDERALBNK.NS','CANBK.NS','PNB.NS'],
    'IT':             ['TCS.NS','INFY.NS','WIPRO.NS','HCLTECH.NS','TECHM.NS','MPHASIS.NS','OFSS.NS','NAUKRI.NS'],
    'Energy':         ['RELIANCE.NS','ONGC.NS','BPCL.NS','IOC.NS','GAIL.NS','TATAPOWER.NS','ATGL.NS'],
    'Auto':           ['MARUTI.NS','TATAMOTORS.NS','M&M.NS','BAJAJ-AUTO.NS','EICHERMOT.NS','HEROMOTOCO.NS','MOTHERSON.NS'],
    'Pharma':         ['SUNPHARMA.NS','CIPLA.NS','DRREDDY.NS','DIVISLAB.NS','LUPIN.NS','AUROPHARMA.NS','TORNTPHARM.NS','BIOCON.NS'],
    'FMCG':           ['HINDUNILVR.NS','ITC.NS','NESTLEIND.NS','BRITANNIA.NS','TATACONSUM.NS','MARICO.NS','COLPAL.NS','GODREJCP.NS'],
    'Metals':         ['TATASTEEL.NS','JSWSTEEL.NS','HINDALCO.NS','COALINDIA.NS','NMDC.NS','SAIL.NS','HINDZINC.NS','VEDL.NS'],
    'Infrastructure': ['LT.NS','ADANIPORTS.NS','ADANIENT.NS','CONCOR.NS','INDUSTOWER.NS','BEL.NS','SIEMENS.NS'],
    'Realty':         ['DLF.NS','GODREJPROP.NS','AMBUJACEM.NS','ULTRACEMCO.NS','SHREECEM.NS','GRASIM.NS'],
    'Finance':        ['BAJFINANCE.NS','BAJAJFINSV.NS','CHOLAFIN.NS','MUTHOOTFIN.NS','SBICARD.NS','ICICIPRULI.NS','SBILIFE.NS','HDFCLIFE.NS','MFSL.NS'],
};

// ── AI signals universe (NIFTY 50 + active F&O additions) ──
const SIG_STOCKS = [
    { sym: 'RELIANCE.NS',   name: 'Reliance Industries',      cls: 'Energy'        },
    { sym: 'TCS.NS',        name: 'Tata Consultancy',         cls: 'IT'            },
    { sym: 'HDFCBANK.NS',   name: 'HDFC Bank',                cls: 'Banking'       },
    { sym: 'INFY.NS',       name: 'Infosys',                  cls: 'IT'            },
    { sym: 'ICICIBANK.NS',  name: 'ICICI Bank',               cls: 'Banking'       },
    { sym: 'HINDUNILVR.NS', name: 'Hindustan Unilever',       cls: 'FMCG'         },
    { sym: 'ITC.NS',        name: 'ITC Limited',              cls: 'FMCG'         },
    { sym: 'SBIN.NS',       name: 'State Bank of India',      cls: 'PSU Banking'   },
    { sym: 'BHARTIARTL.NS', name: 'Bharti Airtel',            cls: 'Telecom'       },
    { sym: 'KOTAKBANK.NS',  name: 'Kotak Mahindra Bank',      cls: 'Banking'       },
    { sym: 'LT.NS',         name: 'Larsen & Toubro',          cls: 'Infrastructure'},
    { sym: 'AXISBANK.NS',   name: 'Axis Bank',                cls: 'Banking'       },
    { sym: 'ASIANPAINT.NS', name: 'Asian Paints',             cls: 'Consumer'      },
    { sym: 'MARUTI.NS',     name: 'Maruti Suzuki',            cls: 'Auto'          },
    { sym: 'TITAN.NS',      name: 'Titan Company',            cls: 'Consumer'      },
    { sym: 'BAJFINANCE.NS', name: 'Bajaj Finance',            cls: 'NBFC'          },
    { sym: 'SUNPHARMA.NS',  name: 'Sun Pharma',               cls: 'Pharma'        },
    { sym: 'WIPRO.NS',      name: 'Wipro',                    cls: 'IT'            },
    { sym: 'HCLTECH.NS',    name: 'HCL Technologies',         cls: 'IT'            },
    { sym: 'BAJAJFINSV.NS', name: 'Bajaj Finserv',            cls: 'NBFC'          },
    { sym: 'NTPC.NS',       name: 'NTPC Limited',             cls: 'Power'         },
    { sym: 'POWERGRID.NS',  name: 'Power Grid Corp',          cls: 'Power'         },
    { sym: 'TECHM.NS',      name: 'Tech Mahindra',            cls: 'IT'            },
    { sym: 'TATAMOTORS.NS', name: 'Tata Motors',              cls: 'Auto'          },
    { sym: 'ADANIENT.NS',   name: 'Adani Enterprises',        cls: 'Conglomerate'  },
    { sym: 'TATASTEEL.NS',  name: 'Tata Steel',               cls: 'Metals'        },
    { sym: 'JSWSTEEL.NS',   name: 'JSW Steel',                cls: 'Metals'        },
    { sym: 'ONGC.NS',       name: 'Oil & Natural Gas',        cls: 'Energy'        },
    { sym: 'HINDALCO.NS',   name: 'Hindalco Industries',      cls: 'Metals'        },
    { sym: 'COALINDIA.NS',  name: 'Coal India',               cls: 'Mining'        },
    { sym: 'EICHERMOT.NS',  name: 'Eicher Motors',            cls: 'Auto'          },
    { sym: 'HEROMOTOCO.NS', name: 'Hero MotoCorp',            cls: 'Auto'          },
    { sym: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto',               cls: 'Auto'          },
    { sym: 'GRASIM.NS',     name: 'Grasim Industries',        cls: 'Cement'        },
    { sym: 'CIPLA.NS',      name: 'Cipla',                    cls: 'Pharma'        },
    { sym: 'DRREDDY.NS',    name: "Dr. Reddy's Labs",         cls: 'Pharma'        },
    { sym: 'DIVISLAB.NS',   name: "Divi's Laboratories",      cls: 'Pharma'        },
    { sym: 'NESTLEIND.NS',  name: 'Nestle India',             cls: 'FMCG'         },
    { sym: 'APOLLOHOSP.NS', name: 'Apollo Hospitals',         cls: 'Healthcare'    },
    { sym: 'TATACONSUM.NS', name: 'Tata Consumer Products',   cls: 'FMCG'         },
    { sym: 'ULTRACEMCO.NS', name: 'UltraTech Cement',         cls: 'Cement'        },
    { sym: 'BPCL.NS',       name: 'Bharat Petroleum',         cls: 'Energy'        },
    { sym: 'ADANIPORTS.NS', name: 'Adani Ports',              cls: 'Logistics'     },
    { sym: 'INDUSINDBK.NS', name: 'IndusInd Bank',            cls: 'Banking'       },
    { sym: 'TRENT.NS',      name: 'Trent',                    cls: 'Retail'        },
    { sym: 'SBILIFE.NS',    name: 'SBI Life Insurance',       cls: 'Insurance'     },
    { sym: 'HDFCLIFE.NS',   name: 'HDFC Life Insurance',      cls: 'Insurance'     },
    { sym: 'SHREECEM.NS',   name: 'Shree Cement',             cls: 'Cement'        },
    { sym: 'M&M.NS',        name: 'Mahindra & Mahindra',      cls: 'Auto'          },
    { sym: 'UPL.NS',        name: 'UPL Limited',              cls: 'Agro'          },
    { sym: 'BRITANNIA.NS',  name: 'Britannia Industries',     cls: 'FMCG'         },
    // NIFTY Next 50 + active F&O additions
    { sym: 'BANKBARODA.NS', name: 'Bank of Baroda',           cls: 'PSU Banking'   },
    { sym: 'PNB.NS',        name: 'Punjab National Bank',     cls: 'PSU Banking'   },
    { sym: 'CANBK.NS',      name: 'Canara Bank',              cls: 'PSU Banking'   },
    { sym: 'UNIONBANK.NS',  name: 'Union Bank of India',      cls: 'PSU Banking'   },
    { sym: 'FEDERALBNK.NS', name: 'Federal Bank',             cls: 'Banking'       },
    { sym: 'IDFCFIRSTB.NS', name: 'IDFC First Bank',          cls: 'Banking'       },
    { sym: 'BANDHANBNK.NS', name: 'Bandhan Bank',             cls: 'Banking'       },
    { sym: 'AUBANK.NS',     name: 'AU Small Finance Bank',    cls: 'Banking'       },
    { sym: 'CHOLAFIN.NS',   name: 'Cholamandalam Finance',    cls: 'NBFC'          },
    { sym: 'LICHSGFIN.NS',  name: 'LIC Housing Finance',      cls: 'NBFC'          },
    { sym: 'MUTHOOTFIN.NS', name: 'Muthoot Finance',          cls: 'NBFC'          },
    { sym: 'PIDILITIND.NS', name: 'Pidilite Industries',      cls: 'Consumer'      },
    { sym: 'BERGEPAINT.NS', name: 'Berger Paints',            cls: 'Consumer'      },
    { sym: 'HAVELLS.NS',    name: 'Havells India',            cls: 'Consumer'      },
    { sym: 'SIEMENS.NS',    name: 'Siemens India',            cls: 'Capital Goods' },
    { sym: 'ABB.NS',        name: 'ABB India',                cls: 'Capital Goods' },
    { sym: 'BOSCHLTD.NS',   name: 'Bosch India',              cls: 'Auto'          },
    { sym: 'CGPOWER.NS',    name: 'CG Power',                 cls: 'Capital Goods' },
    { sym: 'POLYCAB.NS',    name: 'Polycab India',            cls: 'Capital Goods' },
    { sym: 'TATAPOWER.NS',  name: 'Tata Power',               cls: 'Power'         },
    { sym: 'TORNTPHARM.NS', name: 'Torrent Pharma',           cls: 'Pharma'        },
    { sym: 'LUPIN.NS',      name: 'Lupin Limited',            cls: 'Pharma'        },
    { sym: 'BIOCON.NS',     name: 'Biocon Limited',           cls: 'Pharma'        },
    { sym: 'ALKEM.NS',      name: 'Alkem Laboratories',       cls: 'Pharma'        },
    { sym: 'AUROPHARMA.NS', name: 'Aurobindo Pharma',         cls: 'Pharma'        },
    { sym: 'CONCOR.NS',     name: 'Container Corp of India',  cls: 'Logistics'     },
    { sym: 'IRCTC.NS',      name: 'Indian Railway Catering',  cls: 'PSU Services'  },
    { sym: 'RECLTD.NS',     name: 'REC Limited',              cls: 'PSU Finance'   },
    { sym: 'PFC.NS',        name: 'Power Finance Corp',       cls: 'PSU Finance'   },
    { sym: 'BHEL.NS',       name: 'Bharat Heavy Electricals', cls: 'PSU Capital'   },
    { sym: 'SAIL.NS',       name: 'Steel Authority of India', cls: 'Metals'        },
    { sym: 'VEDL.NS',       name: 'Vedanta Limited',          cls: 'Metals'        },
    { sym: 'HINDZINC.NS',   name: 'Hindustan Zinc',           cls: 'Metals'        },
    { sym: 'BALKRISIND.NS', name: 'Balkrishna Industries',    cls: 'Auto'          },
    { sym: 'DEEPAKNTR.NS',  name: 'Deepak Nitrite',           cls: 'Chemicals'     },
    { sym: 'PIIND.NS',      name: 'PI Industries',            cls: 'Agro'          },
    { sym: 'LTIM.NS',       name: 'LTIMindtree',              cls: 'IT'            },
    { sym: 'PERSISTENT.NS', name: 'Persistent Systems',       cls: 'IT'            },
    { sym: 'COFORGE.NS',    name: 'Coforge Limited',          cls: 'IT'            },
    { sym: 'MPHASIS.NS',    name: 'Mphasis Limited',          cls: 'IT'            },
    { sym: 'OFSS.NS',       name: 'Oracle Financial Services',cls: 'IT'            },
    { sym: 'NAUKRI.NS',     name: 'Info Edge (Naukri)',       cls: 'Internet'      },
    { sym: 'ZOMATO.NS',     name: 'Zomato',                   cls: 'Internet'      },
    { sym: 'PAYTM.NS',      name: 'One 97 Comm (Paytm)',      cls: 'Fintech'       },
    { sym: 'ANGELONE.NS',   name: 'Angel One',                cls: 'Fintech'       },
    { sym: 'DMART.NS',      name: 'Avenue Supermarts (DMart)',cls: 'Retail'        },
    { sym: 'PAGEIND.NS',    name: 'Page Industries (Jockey)', cls: 'Consumer'      },
    { sym: 'ASTRAL.NS',     name: 'Astral Limited',           cls: 'Consumer'      },
    { sym: 'LICI.NS',       name: 'LIC of India',             cls: 'Insurance'     },
    { sym: 'ICICIGI.NS',    name: 'ICICI Lombard Insurance',  cls: 'Insurance'     },
    { sym: 'HDFCAMC.NS',    name: 'HDFC AMC',                 cls: 'Asset Mgmt'    },
    { sym: 'TATAELXSI.NS',  name: 'Tata Elxsi',               cls: 'IT'            },
    { sym: 'LTTS.NS',       name: 'L&T Technology Services',  cls: 'IT'            },
    { sym: 'KPITTECH.NS',   name: 'KPIT Technologies',        cls: 'IT'            },
    { sym: 'CYIENT.NS',     name: 'Cyient Limited',           cls: 'IT'            },
    { sym: 'MRF.NS',        name: 'MRF Limited',              cls: 'Auto'          },
    { sym: 'APOLLOTYRE.NS', name: 'Apollo Tyres',             cls: 'Auto'          },
    { sym: 'ESCORTS.NS',    name: 'Escorts Kubota',           cls: 'Auto'          },
    { sym: 'MOTHERSON.NS',  name: 'Samvardhana Motherson',    cls: 'Auto'          },
    { sym: 'ZYDUSLIFE.NS',  name: 'Zydus Lifesciences',       cls: 'Pharma'        },
    { sym: 'IPCALAB.NS',    name: 'IPCA Laboratories',        cls: 'Pharma'        },
    { sym: 'GRANULES.NS',   name: 'Granules India',           cls: 'Pharma'        },
    { sym: 'VOLTAS.NS',     name: 'Voltas Limited',           cls: 'Consumer'      },
    { sym: 'WHIRLPOOL.NS',  name: 'Whirlpool of India',       cls: 'Consumer'      },
    { sym: 'KAJARIA.NS',    name: 'Kajaria Ceramics',         cls: 'Consumer'      },
    { sym: 'SUPREMEIND.NS', name: 'Supreme Industries',       cls: 'Consumer'      },
    { sym: 'NHPC.NS',       name: 'NHPC Limited',             cls: 'Power'         },
    { sym: 'SJVN.NS',       name: 'SJVN Limited',             cls: 'Power'         },
    { sym: 'RVNL.NS',       name: 'Rail Vikas Nigam',         cls: 'Infrastructure'},
    { sym: 'IRFC.NS',       name: 'Indian Railway Finance',   cls: 'PSU Finance'   },
    { sym: 'HUDCO.NS',      name: 'HUDCO',                    cls: 'PSU Finance'   },
    { sym: 'ADANIGREEN.NS', name: 'Adani Green Energy',       cls: 'Power'         },
    { sym: 'NATIONALUM.NS', name: 'National Aluminium',       cls: 'Metals'        },
    { sym: 'HINDCOPPER.NS', name: 'Hindustan Copper',         cls: 'Metals'        },
    { sym: 'MOIL.NS',       name: 'MOIL Limited',             cls: 'Metals'        },
    { sym: 'RBLBANK.NS',    name: 'RBL Bank',                 cls: 'Banking'       },
    { sym: 'SBICARD.NS',    name: 'SBI Cards',                cls: 'Fintech'       },
    { sym: 'ICICIPRULI.NS', name: 'ICICI Prudential Life',    cls: 'Insurance'     },
    { sym: 'MAXHEALTH.NS',  name: 'Max Healthcare',           cls: 'Healthcare'    },
    { sym: 'FORTIS.NS',     name: 'Fortis Healthcare',        cls: 'Healthcare'    },
    { sym: 'NYKAA.NS',      name: 'FSN E-Commerce (Nykaa)',  cls: 'Retail'        },
    { sym: 'POLICYBZR.NS',  name: 'PB Fintech (PolicyBazaar)',cls: 'Fintech'       },
    { sym: 'DELHIVERY.NS',  name: 'Delhivery Limited',        cls: 'Logistics'     },
];

// ── Sector geo-drivers for AI signal cards ──
const CLS_DRIVERS = {
    'Energy':         'Crude oil geopolitical premium · OPEC+ stance',
    'IT':             'USD/INR forex impact · US tech earnings cycle',
    'Banking':        'RBI policy outlook · credit growth momentum',
    'NBFC':           'RBI liquidity stance · credit spreads widening',
    'Auto':           'EV transition pressure · input cost inflation',
    'Conglomerate':   'Multi-sector geo-political exposure',
    'PSU Banking':    'Govt capex cycle · NPA resolution progress',
    'Metals':         'China demand proxy · steel tariff risk',
    'Telecom':        'ARPU expansion · 5G spectrum debt load',
    'FMCG':           'Rural consumption · inflation pass-through',
    'Pharma':         'US FDA approvals · API cost pressures',
    'Healthcare':     'Hospital capex cycle · insurance penetration',
    'Power':          'Renewable transition · grid capacity expansion',
    'Cement':         'Infra capex · real estate demand cycle',
    'Infrastructure': 'Govt capex · PLI scheme momentum',
    'Consumer':       'Premium consumption · discretionary spend',
    'Mining':         'Coal demand · domestic energy security',
    'Insurance':      'Regulatory tailwinds · penetration growth',
    'Logistics':      'Port capacity · trade flow disruptions',
    'Retail':         'Organized retail share gain · tier-2 expansion',
    'Agro':           'Global agri-commodity cycle · kharif season',
};

// ── F&O intraday scanner universe (30 most liquid) ──
const FO_STOCKS = [
    { sym: 'RELIANCE.NS',   name: 'Reliance'     }, { sym: 'HDFCBANK.NS',   name: 'HDFC Bank'    },
    { sym: 'INFY.NS',       name: 'Infosys'      }, { sym: 'TCS.NS',        name: 'TCS'          },
    { sym: 'ICICIBANK.NS',  name: 'ICICI Bank'   }, { sym: 'SBIN.NS',       name: 'SBI'          },
    { sym: 'AXISBANK.NS',   name: 'Axis Bank'    }, { sym: 'KOTAKBANK.NS',  name: 'Kotak Bank'   },
    { sym: 'BAJFINANCE.NS', name: 'Bajaj Finance'}, { sym: 'TATAMOTORS.NS', name: 'Tata Motors'  },
    { sym: 'TATASTEEL.NS',  name: 'Tata Steel'   }, { sym: 'WIPRO.NS',      name: 'Wipro'        },
    { sym: 'HCLTECH.NS',    name: 'HCL Tech'     }, { sym: 'SUNPHARMA.NS',  name: 'Sun Pharma'   },
    { sym: 'ONGC.NS',       name: 'ONGC'         }, { sym: 'MARUTI.NS',     name: 'Maruti'       },
    { sym: 'ADANIPORTS.NS', name: 'Adani Ports'  }, { sym: 'HINDALCO.NS',   name: 'Hindalco'     },
    { sym: 'NTPC.NS',       name: 'NTPC'         }, { sym: 'POWERGRID.NS',  name: 'Power Grid'   },
    { sym: 'TECHM.NS',      name: 'Tech Mahindra'}, { sym: 'BHARTIARTL.NS', name: 'Airtel'       },
    { sym: 'BPCL.NS',       name: 'BPCL'         }, { sym: 'GRASIM.NS',     name: 'Grasim'       },
    { sym: 'INDUSINDBK.NS', name: 'IndusInd Bank'}, { sym: 'VEDL.NS',       name: 'Vedanta'      },
    { sym: 'TATAPOWER.NS',  name: 'Tata Power'   }, { sym: 'BANKBARODA.NS', name: 'Bank of Baroda'},
    { sym: 'ZOMATO.NS',     name: 'Zomato'       }, { sym: 'LTIM.NS',       name: 'LTIMindtree'  },
];

// ── Namit's personal trader profile (FY24-FY26 trade data) ──
const TRADER_EDGE = {
    totalTrades:    3121,    overallWR:      41.5,
    intradayWR:     43,      intradayPnl:    1233970,
    overnightPnl:  -463079,  multidayPnl:   -2671715,
    monthly: [
        { m: 'Jan', wr: 46, pnl: -443929  },
        { m: 'Feb', wr: 28, pnl: -1597548 }, // worst month
        { m: 'Mar', wr: 40, pnl: -161287  },
        { m: 'Apr', wr: 46, pnl:   70660  },
        { m: 'May', wr: 43, pnl: -143714  },
        { m: 'Jun', wr: 58, pnl:   99250  },
        { m: 'Jul', wr: 37, pnl: -508254  },
        { m: 'Aug', wr: 33, pnl: -380342  },
        { m: 'Sep', wr: 36, pnl: -401322  },
        { m: 'Oct', wr: 36, pnl: -140813  },
        { m: 'Nov', wr: 49, pnl:  605711  },
        { m: 'Dec', wr: 51, pnl: 1100763  }, // best month
    ],
    edgeStocks:   ['IRCTC','AMBUJACEM','NATIONALUM','ADANIPORTS','NMDC','BSOFT','ICICIBANK','TATAMOTORS','SAIL','COALINDIA','TITAN','ITC'],
    avoidStocks:  ['RELIANCE','SENSEX','BEL','JSWSTEEL','TATASTEEL','IDEA','SRF','PVRINOX','ASHOKLEY','BANKEX'],
    premiumEdge: [
        { range: '5–15',    wr: 31, pnl:  106169, intradayPnl:  334518 },
        { range: '15–30',   wr: 39, pnl:  603550, intradayPnl:  154376 },
        { range: '100–200', wr: 57, pnl: -1373555, intradayPnl: 198710 },
        { range: '>200',    wr: 66, pnl:  219737, intradayPnl:  419534 },
    ],
    intradayPremiumBest: { range: '>200', wr: 78, pnl: 419534 },
    worstHabit: 'Averaging down: 626 positions, -₹5.3L total loss',
};

module.exports = {
    NSE_FNO_LIQUID,
    NIFTY100_LIST,
    NSE_KEY_IDX,
    NSE_IDX_MAP,
    COUNTRY_INDICES,
    SECTOR_MAP,
    SIG_STOCKS,
    CLS_DRIVERS,
    FO_STOCKS,
    TRADER_EDGE,
};
